### PR TITLE
Add IMU Code

### PR DESCRIPTION
**Pull request by joshua000**
Uses the documentation provided to read IMU data.

### CODE REVIEW

**Comment by joshua000** [comment]
Also is it even an IMU?? Cant really find anything definitive, but idk if we want to keep calling it an IMU if its not.

**Comment by LRitzdorf** [comment]
Oh. Uh, quick note, this isn't quite the proper way to merge a PR...

Usually, you just use the Merge button in GitHub, then pull down the new merge commit to your clone. Alternatively, if you choose to merge manually (as you did here), don't mark the PR as closed, since that usually means it was abandoned. When you push an appropriate merge commit, GitHub should automatically mark the PR as merged for you

**Comment by joshua000** [comment]
This was abandoned. I just edited the acual code rather than the clone.

**Comment by LRitzdorf** [comment]
Ah, right, you'd have write access to both. :man_facepalming:

**Comment by LRitzdorf** [comment]
Ah, right, you'd have write access to both. :man_facepalming:

**Pull request closed without merging**
